name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: print hello
        run: echo "hello there"
      - name: print goodbye
        run: echo "goodbye"
